### ISSUE TITLE
Publish it to the Chrome Store?

### ISSUE THREAD

**Issue by deadcoder0904** [oslabs-beta/deValtio#63]
Bcz why not?

**Comment by deadcoder0904** [comment]
also, it's not working. i just downloaded it & added it to chrome but see blank screen

**Comment by cwalls45** [comment]
We are currently still working out a few issues before we publish to the Chrome store. 

When you downloaded the extension, make sure you take the following steps: 

1.  npm install
2. npm run build
3. press the reload button on chrome://extensions

This should elevate the problem!

**Comment by deadcoder0904** [comment]
cool, i went with redux dev tools as i only wanted to see the state 👍
